// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// prox_sorted_L1_C
NumericVector prox_sorted_L1_C(NumericVector y, NumericVector lambda);
RcppExport SEXP SLOPE_prox_sorted_L1_C(SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(prox_sorted_L1_C(y, lambda));
    return __result;
END_RCPP
}
